// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIDcNfbwKpvUk4oor4J97E7eihHkCUU8k',
    appId: '1:729246064126:web:b009b94248e096d6f474af',
    messagingSenderId: '729246064126',
    projectId: 'warmindo-api',
    authDomain: 'warmindo-api.firebaseapp.com',
    storageBucket: 'warmindo-api.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrTYliMwb6HxE2i9NfQ31a_b-B7TGAPuw',
    appId: '1:729246064126:android:0be21d0f08ea6119f474af',
    messagingSenderId: '729246064126',
    projectId: 'warmindo-api',
    storageBucket: 'warmindo-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-zqKprFXt_92m2jxZSU7RabL37hJ0JZs',
    appId: '1:729246064126:ios:5f88eaf5d2cfc723f474af',
    messagingSenderId: '729246064126',
    projectId: 'warmindo-api',
    storageBucket: 'warmindo-api.appspot.com',
    iosClientId: '729246064126-6drqum7u2keqaj6o5240r1np3aed8nf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.warmindoAdminUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-zqKprFXt_92m2jxZSU7RabL37hJ0JZs',
    appId: '1:729246064126:ios:5f88eaf5d2cfc723f474af',
    messagingSenderId: '729246064126',
    projectId: 'warmindo-api',
    storageBucket: 'warmindo-api.appspot.com',
    iosClientId: '729246064126-6drqum7u2keqaj6o5240r1np3aed8nf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.warmindoAdminUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIDcNfbwKpvUk4oor4J97E7eihHkCUU8k',
    appId: '1:729246064126:web:981c3159d41d7b03f474af',
    messagingSenderId: '729246064126',
    projectId: 'warmindo-api',
    authDomain: 'warmindo-api.firebaseapp.com',
    storageBucket: 'warmindo-api.appspot.com',
  );
}
